---
title: "GSEA protein and RNA"
author: "Kaspar Bresser"
date: "14/08/2025"
output: 
  github_document:
    toc: true
  html_document: 
    theme: simplex
    highlight: pygments
#    code_folding: show
    self_contained: TRUE
    toc: yes
    toc_float:
      collapsed: no
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      autodep  = TRUE,
                      cache = FALSE,
                      fig.width = 5,
                      fig.asp = 0.618,
                      fig.align = "center")
```



```{r loading, echo=FALSE}
library(tidyverse)
library(rstatix)
library(lemon)
library(ggpubr)
library(clusterProfiler)
library(ReactomePA)
library(org.Hs.eg.db)
library(msigdbr)
library(tidytext)
```




## Import data

```{r}
dat.combined <- read_tsv( "Output/data_combined.tsv")
dat.DE.all <- read_tsv("Output/data_DE_all.tsv")

```




## Pathway testing


set function for testing. Will use ClusterProfiler package. Function will test both RNA and protein level, and output a tibble with the results of both. 

```{r}
test_pathways <- function(dat, pathways, comp){
  
  # get prot FC
  dat %>% 
    filter(comparison == comp) %>% 
    dplyr::select(gene.symbol, logFC.prot) -> dat.prot
  
  # Get RNA FC
  dat %>% 
    filter(comparison == comp) %>% 
    dplyr::select(gene.symbol, logFC.rna) -> dat.rna
  
  # Make vector of pathway  symbols
  paths <-  pathways[, c("gs_name", "gene_symbol")]
  
  # Make vector of protein FCs
  gene.list.vec <- dat.prot$logFC.prot
  names(gene.list.vec) <- dat.prot$gene.symbol
  gene.list.vec <- sort(gene.list.vec, decreasing = TRUE)


 # test for pathways in proteins
  gsea.res.prot <- GSEA(
    geneList = gene.list.vec, # logFC ranked
    TERM2GENE = paths,
    pvalueCutoff = 0.05)
  
  # make vector of RNA FCs
  gene.list.vec <- dat.rna$logFC.rna
  names(gene.list.vec) <- dat.rna$gene.symbol
  gene.list.vec <- sort(gene.list.vec, decreasing = TRUE)

  # Test for pathways in RNA
  gsea.res.rna <- GSEA(
    geneList = gene.list.vec, # logFC ranked
    TERM2GENE = paths,
    pvalueCutoff = 0.05)
  
  # Output dataframe
  bind_rows(
    as.data.frame(gsea.res.rna) %>% mutate(metric = "RNA"),
    as.data.frame(gsea.res.prot) %>% mutate(metric = "protein")) %>%
   # dplyr::select(Description, metric, NES, p.adjust) %>% 
    mutate(comparison = comp)
  
}
```



Get Hallmark pathways

```{r}
pathways <- msigdbr(species = "Homo sapiens", db_species = "HS", collection = "H")
```


map the function over the different comparisons (populations)

```{r}
dat.DE.all %>% 
  pull(comparison) %>% 
  unique() %>% 
  map(~test_pathways(dat = dat.DE.all, pathways = pathways, comp = .)) %>% 
  list_rbind() -> results.hallmark

```


Reorder the pathway names and tidy up

```{r}
results.hallmark %>%
  mutate(Description = str_remove(Description, "HALLMARK_") ) %>%
  group_by(comparison, Description) %>%
  mutate(presence = case_when(any(metric == "RNA") & any(metric == "protein") ~ 1,
                               any(metric == "RNA")                            ~ 2,
                               any(metric == "protein")                        ~ 3)) %>%
  ungroup() %>% 
  mutate(Description_ord = reorder_within(Description,
                                          presence * 100 - NES,
                                          comparison)) -> to.plot

to.plot
```

Output data

```{r}
write_tsv(to.plot, "Output/GSEA_pathways_Hallmark.tsv")
```



And plot
 

```{r fig.width= 13, fig.asp = .35}

ggplot(to.plot, aes(x = fct_rev(metric), y = fct_rev(Description_ord), size = -log10(p.adjust), fill = NES))+
  geom_point(color = "black", shape = 21) +
  scale_fill_gradient2(low = "#377eb8", mid = "white", high = "#e41a1c", midpoint = 0)+
  scale_size(range = c(2, 10))+
  facet_rep_wrap(~comparison, scales = "free_y")+
  tidytext::scale_y_reordered() +
  theme_classic() +
  labs(color = "NES", size = "-log10(adj P)", x = NULL, y = NULL, title = "Hallmark pathways")+
  theme(panel.grid.major = element_line(color = "grey90"))

ggsave("Figs/GSEA_Hallmark_all.pdf", height = 5.6, width = 12.5)
```


